CREATE TABLE guilds ();
CREATE TABLE users ();
CREATE TABLE highlights ();
CREATE TABLE _migrations ();
ALTER TABLE guilds ADD COLUMN id BIGINT;
ALTER TABLE users ADD COLUMN id BIGINT;
ALTER TABLE highlights ADD COLUMN id SERIAL;
ALTER TABLE highlights ADD COLUMN user_id BIGINT;
ALTER TABLE highlights ADD COLUMN guild_id BIGINT;
ALTER TABLE highlights ADD COLUMN content TEXT;
ALTER TABLE highlights ADD COLUMN is_regex BOOLEAN;
ALTER TABLE highlights ADD COLUMN channel_list BIGINT[];
ALTER TABLE highlights ADD COLUMN channel_list_is_blacklist BOOLEAN;
ALTER TABLE highlights ADD COLUMN user_list BIGINT[];
ALTER TABLE highlights ADD COLUMN user_list_is_blacklist BOOLEAN;
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE guilds ALTER COLUMN id SET NOT NULL;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN guild_id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN content SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN is_regex SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN channel_list SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN channel_list_is_blacklist SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN user_list SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN user_list_is_blacklist SET NOT NULL;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
ALTER TABLE highlights ADD CONSTRAINT content_user_guild_uq UNIQUE ( user_id , guild_id , content );
ALTER TABLE guilds ADD CONSTRAINT _guilds_id_primary_key PRIMARY KEY ( id );
ALTER TABLE users ADD CONSTRAINT _users_id_primary_key PRIMARY KEY ( id );
ALTER TABLE highlights ADD CONSTRAINT _highlights_id_primary_key PRIMARY KEY ( id );
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );
ALTER TABLE highlights ADD CONSTRAINT user_id_fk FOREIGN KEY ( user_id ) REFERENCES users ( id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE highlights ADD CONSTRAINT guild_id_fk FOREIGN KEY ( guild_id ) REFERENCES guilds ( id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;