CREATE TABLE users ();
CREATE TABLE highlights ();
CREATE TABLE _migrations ();
ALTER TABLE users ADD COLUMN id BIGINT;
ALTER TABLE highlights ADD COLUMN id SERIAL;
ALTER TABLE highlights ADD COLUMN user_id BIGINT;
ALTER TABLE highlights ADD COLUMN is_regex BOOLEAN;
ALTER TABLE highlights ADD COLUMN content TEXT;
ALTER TABLE highlights ADD COLUMN guild_list BIGINT[];
ALTER TABLE highlights ADD COLUMN guild_list_mode SMALLINT;
ALTER TABLE _migrations ADD COLUMN id_ INTEGER;
ALTER TABLE users ALTER COLUMN id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN user_id SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN is_regex SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN content SET NOT NULL;
ALTER TABLE highlights ALTER COLUMN guild_list_mode SET NOT NULL;
ALTER TABLE _migrations ALTER COLUMN id_ SET NOT NULL;
CREATE INDEX _btree_index_highlights__guild_list ON highlights USING BTREE ( ( guild_list ) );
ALTER TABLE highlights ADD CONSTRAINT content_user_uq UNIQUE ( user_id , content );
ALTER TABLE users ADD CONSTRAINT _users_id_primary_key PRIMARY KEY ( id );
ALTER TABLE highlights ADD CONSTRAINT _highlights_id_primary_key PRIMARY KEY ( id );
ALTER TABLE _migrations ADD CONSTRAINT __migrations_id__primary_key PRIMARY KEY ( id_ );
ALTER TABLE highlights ADD CONSTRAINT user_id_fk FOREIGN KEY ( user_id ) REFERENCES users ( id ) MATCH SIMPLE ON DELETE CASCADE ON UPDATE CASCADE;